export const IMAGE_SIZE = 512;
export const BACKGROUND_IMAGE_SIZE_DIVIDER = 8;
export const ASSETS = [
    "coloring/fruits/apple",
    "coloring/fruits/banana",
    "coloring/fruits/carrot",
    "coloring/fruits/cauliflower",
    "coloring/fruits/strawberry",
    "coloring/fruits/corn",
    "coloring/fruits/grapes",
    "coloring/fruits/mushroom",
    "coloring/fruits/orange",
    "coloring/fruits/pear",
    "coloring/fruits/peas",
    "coloring/fruits/pineapple",
    "coloring/fruits/plum",
    "coloring/fruits/aubergine",
    "coloring/fruits/blueberries",
    "coloring/fruits/broccoli",
    "coloring/fruits/cherries",
    "coloring/fruits/coconut",
    "coloring/fruits/tomato",
    "coloring/critters/butterfly",
    "coloring/critters/caterpillar",
    "coloring/critters/dragonfly",
    "coloring/critters/ladybug",
    "coloring/critters/scorpion",
    "coloring/critters/snail",
    "coloring/critters/spider",
    "coloring/critters/worm",
    "coloring/animals/panda",
    "coloring/animals/owl",
    "coloring/animals/hippo",
    "coloring/animals/rhino",
    "coloring/animals/frog",
];
